### ISSUE TITLE
Issue in price feeds level

### ISSUE THREAD

**Issue by shikhar229169** [Chainiversity/chainiversity-dapp#2]
In the price feeds manager contract, getLatestPrice() function and getValidatedValue() must be made private as the user can directly call these functions.
Below is the screenshot which shows the implementation:

![image](https://github.com/Chainiversity/chainiversity-dapp/assets/111875681/e1321d00-006b-45a9-8804-2d0011e2b38e)

**Comment by egeaybars123** [comment]
Fixed it in the latest commit. Thanks for pointing this out!
